# Generated by Django 5.2 on 2026-04-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_managers_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signdictionary',
            name='categorie',
            field=models.CharField(choices=[('ALPHABET', 'Alphabet'), ('CHIFFRE', 'Chiffre')], default='ALPHABET', max_length=20),
        ),
    ]
